# index_workspace.ps1
# Antigravity Workspace Indexer v1.1
# Regenerates workspace/WORKSPACE_INDEX.md with a clean directory tree.
# Usage: powershell -ExecutionPolicy Bypass -File "...\index_workspace.ps1"

param(
    [string]$RootPath  = "c:\Users\steph\Desktop\Antigravity and Agent 0",
    [string]$OutputPath = "c:\Users\steph\Desktop\Antigravity and Agent 0\workspace\WORKSPACE_INDEX.md"
)

# ─── Exclusions ───────────────────────────────────────────────────────────────
$EXCLUDED = @(
    "node_modules", ".git", ".next", "dist", "__pycache__",
    ".vscode", "target", "build", ".nuxt", "coverage", ".cache"
)

# ─── Helpers ──────────────────────────────────────────────────────────────────
function ShouldExclude([string]$name) {
    return $EXCLUDED -contains $name
}

function FmtSize([long]$bytes) {
    if ($bytes -ge 1MB) { return ("{0:N1} MB" -f ($bytes / 1MB)) }
    if ($bytes -ge 1KB) { return ("{0:N0} KB" -f ($bytes / 1KB)) }
    return ("{0} B" -f $bytes)
}

function BuildTree([string]$path, [int]$depth = 0, [int]$maxDepth = 4) {
    if ($depth -ge $maxDepth) { return @() }

    $result = [System.Collections.Generic.List[string]]::new()
    $pad    = "    " * $depth

    try {
        $items = Get-ChildItem -Path $path -Force -ErrorAction Stop |
            Where-Object { -not (ShouldExclude $_.Name) } |
            Sort-Object -Property @{Expression={-not $_.PSIsContainer}}, Name

        foreach ($item in $items) {
            if ($item.PSIsContainer) {
                $result.Add("${pad}+-- [DIR] $($item.Name)/")
                $sub = BuildTree $item.FullName ($depth + 1) $maxDepth
                foreach ($s in $sub) { $result.Add($s) }
            } else {
                $sz = FmtSize $item.Length
                $result.Add("${pad}+-- $($item.Name)  ($sz)")
            }
        }
    } catch {
        $result.Add("${pad}+-- [access denied]")
    }

    return $result.ToArray()
}

# ─── Build output ─────────────────────────────────────────────────────────────
$ts     = Get-Date -Format "yyyy-MM-ddTHH:mmZ"
$lines  = [System.Collections.Generic.List[string]]::new()

$lines.Add("# Workspace Index")
$lines.Add("")
$lines.Add("> Auto-generated by index_workspace.ps1 | Last updated: $ts")
$lines.Add("> Do NOT edit manually. Run /update-index to regenerate.")
$lines.Add("")
$lines.Add("---")
$lines.Add("")
$lines.Add("## Root Files")
$lines.Add("")
$lines.Add("| File | Size | Notes |")
$lines.Add("|------|------|-------|")

$rootFiles = Get-ChildItem -Path $RootPath -File -Force |
    Where-Object { -not (ShouldExclude $_.Name) } |
    Sort-Object Name

foreach ($f in $rootFiles) {
    $note = switch ($f.Name) {
        ".env"                 { "SECRETS - never commit" }
        "mcp config.json"      { "MCP server config" }
        "start_agent_zero.bat" { "Agent Zero launcher" }
        "watchdog.bat"         { "Process watchdog" }
        "validate_xml.py"      { "XML validator" }
        "voice_bypass.py"      { "Voice bypass" }
        default                { "" }
    }
    $sz = FmtSize $f.Length
    $lines.Add("| $($f.Name) | $sz | $note |")
}

$lines.Add("")
$lines.Add("---")
$lines.Add("")

# Top-level directories to index
$TOP_DIRS = @("workspace", "projects", ".agent", "agents", "comms", "ops", "reports")

foreach ($dir in $TOP_DIRS) {
    $dirPath = Join-Path $RootPath $dir
    if (-not (Test-Path $dirPath)) { continue }

    $lines.Add("## $dir/")
    $lines.Add("")
    $lines.Add('```')
    $tree = BuildTree $dirPath 0 5
    foreach ($t in $tree) { $lines.Add($t) }
    $lines.Add('```')
    $lines.Add("")
    $lines.Add("---")
    $lines.Add("")
}

# ─── Dead Weight ──────────────────────────────────────────────────────────────
$lines.Add("## Known Dead Weight")
$lines.Add("")
$lines.Add("| Path | Status |")
$lines.Add("|------|--------|")

$dw = @(
    [pscustomobject]@{ Path = "agent-manager-skill/";                                     Status = "Empty - unused" }
    [pscustomobject]@{ Path = "agent_zero/";                                               Status = "Empty - unused" }
    [pscustomobject]@{ Path = "workspace/agents/";                                         Status = "Empty - unused" }
    [pscustomobject]@{ Path = "-p/";                                                       Status = "Accidental empty dir" }
    [pscustomobject]@{ Path = "projects/Sonic_Reader/sonic_reader_web/";                   Status = "Empty" }
    [pscustomobject]@{ Path = "workspace/projects/norcast-seminar-page/NorCast Seminar-*/";Status = "Archive duplicate" }
    [pscustomobject]@{ Path = ".../www/inc - Copy/";                                       Status = "Backup duplicate" }
    [pscustomobject]@{ Path = "projects/morgenrapport-triage/frontend/src/";               Status = "No source files" }
)

foreach ($entry in $dw) {
    $lines.Add("| $($entry.Path) | $($entry.Status) |")
}

$lines.Add("")
$lines.Add("---")
$lines.Add("")
$lines.Add("_Generated by workspace/skills/index_workspace.ps1 -- Antigravity v2.13_")

# ─── Write file ───────────────────────────────────────────────────────────────
$lines | Out-File -FilePath $OutputPath -Encoding UTF8 -Force
Write-Host "WORKSPACE_INDEX.md updated: $OutputPath" -ForegroundColor Green
Write-Host "Timestamp: $ts" -ForegroundColor Cyan
