# Heartbeat Runner (PowerShell)
# Triggered by Windows Task Scheduler every 30 minutes.
# Performs workspace maintenance as defined in workspace/heartbeat.md.

$BaseDir = "c:\Users\steph\Desktop\Antigravity and Agent 0"
$MemoryDir = Join-Path $BaseDir "workspace\memory"
$LogsDir = Join-Path $MemoryDir "logs"
$SessionFile = Join-Path $MemoryDir "session_$(Get-Date -Format 'yyyy-MM-dd').md"
$ErrorLog = Join-Path $LogsDir "error.log"

# Ensure directories exist
New-Item -ItemType Directory -Path $LogsDir -Force | Out-Null

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$isoTimestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"
$StateFile = Join-Path $BaseDir "workspace\state.json"

# 0. State Update: Update heartbeat in state.json
if (Test-Path $StateFile) {
    $state = Get-Content $StateFile | ConvertFrom-Json
    $state.heartbeat_count = [int]$state.heartbeat_count + 1
    $state.last_heartbeat = $isoTimestamp
    $state.last_updated = $isoTimestamp
    $state | ConvertTo-Json -Depth 10 | Set-Content $StateFile -Encoding UTF8
    Write-Host "[$timestamp] Heartbeat count updated in state.json"
}

# 1. Memory Maintenance: Ensure today's session file exists
if (-not (Test-Path $SessionFile)) {
    $header = "# Session Log: $(Get-Date -Format 'yyyy-MM-dd')`n`n## Auto-generated by heartbeat at $timestamp`n"
    Set-Content -Path $SessionFile -Value $header -Encoding UTF8
    Write-Host "[$timestamp] Created session file: $SessionFile"
} else {
    Write-Host "[$timestamp] Session file exists: $SessionFile"
}

# 2. Cron Health Check: Scan for NEW errors only
$OffsetFile = Join-Path $LogsDir ".last_error_offset"
if (Test-Path $ErrorLog) {
    $currentSize = (Get-Item $ErrorLog).Length
    $lastSize = 0
    if (Test-Path $OffsetFile) {
        $lastSize = [int](Get-Content $OffsetFile -Raw).Trim()
    }
    if ($currentSize -gt $lastSize) {
        Write-Host "[$timestamp] WARNING: New errors detected in error.log (${lastSize} -> ${currentSize} bytes)"
        Add-Content -Path $SessionFile -Value "`n## Heartbeat Alert ($timestamp)`n- New errors detected in error.log since last cycle. Review required.`n"
    } else {
        Write-Host "[$timestamp] No new errors since last cycle."
    }
    # Update offset to current size
    Set-Content -Path $OffsetFile -Value $currentSize -Encoding UTF8
} else {
    Write-Host "[$timestamp] No error log found. All clear."
    if (Test-Path $OffsetFile) { Remove-Item $OffsetFile }
}

# 3. Night Watch Check: Trigger if QUEUED tasks exist
$NightWatchPath = Join-Path $BaseDir "workspace\protocols\night_watch.md"
if (Test-Path $NightWatchPath) {
    $content = Get-Content $NightWatchPath -Raw
    if ($content -match "QUEUED") {
        Write-Host "[$timestamp] QUEUED tasks found. Triggering Night Watch..."
        python (Join-Path $BaseDir "workspace\skills\night_watch_heartbeat.py") --once
    } else {
        Write-Host "[$timestamp] No QUEUED tasks in Night Watch."
    }
}

# 4. Security: Verify .env is not tracked by git
$gitignorePath = Join-Path $BaseDir ".gitignore"
if (Test-Path $gitignorePath) {
    $gitignoreContent = Get-Content $gitignorePath -Raw
    if ($gitignoreContent -notmatch "\.env") {
        Write-Host "[$timestamp] SECURITY WARNING: .env is NOT in .gitignore!"
        Add-Content -Path $SessionFile -Value "`n## Security Alert ($timestamp)`n- .env is NOT excluded by .gitignore!`n"
    }
}

Write-Host "[$timestamp] Heartbeat cycle complete."
