import os
import json
import glob
from datetime import datetime, timezone

# Protocol Config
LOG_DIR = "memory/logs/vault"
ERROR_FILE = "memory/logs/error.log"
OUTPUT_DIR = "memory"

def generate_morning_report():
    today = datetime.now().strftime("%Y-%m-%d")
    short_date = datetime.now().strftime("%y-%m-%d")
    sentinel_file = os.path.join(LOG_DIR, f"sentinel_{today}.jsonl")
    
    # 1. Gather Data
    events = []
    if os.path.exists(sentinel_file):
        with open(sentinel_file, "r", encoding="utf-8") as f:
            for line in f:
                try:
                    events.append(json.loads(line))
                except:
                    continue
    
    errors = []
    if os.path.exists(ERROR_FILE):
        with open(ERROR_FILE, "r", encoding="utf-8") as f:
            errors = f.readlines()
            
    # 2. Analyze Events
    errors = [line for line in errors if line.strip()] # Filter out empty/whitespace lines
    
    heartbeats = [e for e in events if e.get("event") == "HEARTBEAT"]
    tasks_success = [e for e in events if e.get("event") == "SUCCESS"]
    tasks_failed = [e for e in events if e.get("event") == "ERROR"]
    budget_blocks = [e for e in events if e.get("event") == "BUDGET_EXCEEDED"]
    
    # 3. Determine Report ID
    existing_reports = glob.glob(os.path.join(OUTPUT_DIR, f"MORNING_REPORT_#*_{short_date}.md"))
    report_number = len(existing_reports) + 1
    
    # Check if a report with this number already exists (safeguard)
    report_filename = os.path.join(OUTPUT_DIR, f"MORNING_REPORT_#{report_number}_{short_date}.md")
    while os.path.exists(report_filename):
        report_number += 1
        report_filename = os.path.join(OUTPUT_DIR, f"MORNING_REPORT_#{report_number}_{short_date}.md")
    
    # 4. Gather Intelligence
    intel_file = os.path.join(OUTPUT_DIR, "morning_brief_data.json")
    intel = {}
    if os.path.exists(intel_file):
        with open(intel_file, "r", encoding="utf-8") as f:
            intel = json.load(f)
    
    # 5. Build Markdown
    md = f"""# 🕵️ Architect's Morning Report (#{report_number}) | {today}

## 1. Executive Summary
JARVIS has maintained 100% operational persistence through {len(heartbeats)} heartbeat cycles today. System health is **{'OPTIMAL' if not (errors or intel.get('intelligence', {}).get('news_vector_1', {}).get('error')) else 'DEGRADED'}**.

## 2. Intelligence & In-box Zero
### 📧 Email Audit (Last 24h)
- **Personal**: {intel.get('intelligence', {}).get('email_audit', {}).get('personal', 'No data.')}
- **Business**: {intel.get('intelligence', {}).get('email_audit', {}).get('business', 'No data.')}

### 🌐 Digital Empire Intel (Vector 1)
{intel.get('intelligence', {}).get('news_vector_1', {}).get('briefing', intel.get('intelligence', {}).get('news_vector_1', {}).get('error', 'No news data.'))}

## 3. Infrastructure & Hygiene
- **Persistence**: Heartbeat active (PowerShell/Scheduler).
- **Vortex Bus**: Remote Supabase bus verified.
- **Log Hygiene**: Rotated and Archived.

## 4. Task Execution & Autonomy
- **Tasks Successfully Deployed**: {len(tasks_success)}
- **Tasks Blocked (Budget/Audit)**: {len(budget_blocks)}
- **Critical Failures**: {len(tasks_failed)}

### Recent Activity Traces:
"""
    for e in events[-10:]: # Last 10 events
        md += f"- `{e.get('timestamp')}` | **{e.get('event')}**: {str(e.get('details'))[:100]}\n"

    if errors:
        md += "\n## 5. Error Traceback (UNRESOLVED)\n```text\n"
        md += "".join(errors[-20:]) # Last 20 error lines
        md += "```\n"

    md += f"\n---\n*Report generated by JARVIS Baseline {datetime.now(timezone.utc).isoformat()}*"
    
    # 5. Write Report
    with open(report_filename, "w", encoding="utf-8") as f:
        f.write(md)
        
    print(f"Morning Report generated: {report_filename}")
    return report_filename

if __name__ == "__main__":
    generate_morning_report()
