/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MilestoneStatus = IDL.Text;
export const MilestoneColor = IDL.Text;
export const Milestone = IDL.Record({
  'id' : IDL.Nat,
  'status' : MilestoneStatus,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'color' : MilestoneColor,
  'step' : IDL.Text,
  'description' : IDL.Text,
});
export const Stats = IDL.Record({
  'total' : IDL.Nat,
  'completed' : IDL.Nat,
  'remaining' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMilestone' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteMilestone' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
  'getMilestone' : IDL.Func([IDL.Nat], [IDL.Opt(Milestone)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'updateMilestone' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MilestoneStatus = IDL.Text;
  const MilestoneColor = IDL.Text;
  const Milestone = IDL.Record({
    'id' : IDL.Nat,
    'status' : MilestoneStatus,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'color' : MilestoneColor,
    'step' : IDL.Text,
    'description' : IDL.Text,
  });
  const Stats = IDL.Record({
    'total' : IDL.Nat,
    'completed' : IDL.Nat,
    'remaining' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMilestone' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteMilestone' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
    'getMilestone' : IDL.Func([IDL.Nat], [IDL.Opt(Milestone)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'updateMilestone' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };